/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#ifndef MY_COMMAND_ISR
#define MY_COMMAND_ISR
    
#include "cytypes.h" /* For data types? */
//#include "CyLib.h" /*For delays? */
#include "XBee_UART.h"
#include <project.h>
	
//#include "MagBaseFunctions.h"
#include "DriverMAG3110.h"
    
	
	//DEFINE CMD CODE VALUES
	
	/* START: COMMAND CODE RANGES */
		//INBOUND
		#define START_OF_CMD_CODE_VALUES				(1u)
		
		#define RANGESIZE_WRITEMULT_TYPE				(1u)
	
		#define STARTOFRANGE_SET_SAMPLING_AND_RATE		(CMD_I_WM_OFFSET_ALL + RANGESIZE_WRITEMULT_TYPE) //2
		#define RANGESIZE_SET_SAMPLING_AND_RATE			(32u)
	
		#define STARTOFRANGE_READ_TYPE					(STARTOFRANGE_SET_SAMPLING_AND_RATE+RANGESIZE_SET_SAMPLING_AND_RATE) //34
		#define RANGESIZE_READ_TYPE						(7u)

		#define STARTOFRANGE_SET_CTRL1_OTHER_TYPE		(STARTOFRANGE_READ_TYPE+RANGESIZE_READ_TYPE) //41
		#define RANGESIZE_SET_CTRL1_OTHER_TYPE			(7u)

		#define STARTOFRANGE_SET_CTRL2_TYPE				(STARTOFRANGE_SET_CTRL1_OTHER_TYPE + RANGESIZE_SET_CTRL1_OTHER_TYPE) //48
		#define RANGESIZE_SET_CTRL2_TYPE				(6u)

		// RESET ALL
		//#define CMD_I_RESET_ALL							(54u)
	
		// OUTBOUND
		#define STARTOFRANGE_OUTBOUND_CMD				(STARTOFRANGE_SET_CTRL2_TYPE+RANGESIZE_SET_CTRL2_TYPE+1) //54
		#define RANGESIZE_OUTBOUND_CMD					(6u)
	/* END: COMMAND CODE RANGES in 'const uint8'*/

	
	/* START: COMMAND CODE VALUES in 'const uint8'*/
		/* INBOUND CMD [WRITE] (MULTIBYTE) [Format: {CMD_I_WM_...} ] */
		#define	CMD_I_WM_OFFSET_ALL						(1u) //START_OF_CMD_CODE_VALUES = 1u

		/* INBOUND CMD [WRITE] (SINGLE BYTE) */
		#define	CMD_I_WS_SAMPLING_RATE_A0				(STARTOFRANGE_SET_SAMPLING_AND_RATE+0) // STARTOFRANGE_SET_SAMPLING_AND_RATE = 2u
		#define	CMD_I_WS_SAMPLING_RATE_A1				(STARTOFRANGE_SET_SAMPLING_AND_RATE+1)
		#define	CMD_I_WS_SAMPLING_RATE_A2				(STARTOFRANGE_SET_SAMPLING_AND_RATE+2)
		#define	CMD_I_WS_SAMPLING_RATE_A3				(STARTOFRANGE_SET_SAMPLING_AND_RATE+3)
		#define	CMD_I_WS_SAMPLING_RATE_A4				(STARTOFRANGE_SET_SAMPLING_AND_RATE+4)
		#define	CMD_I_WS_SAMPLING_RATE_A5				(STARTOFRANGE_SET_SAMPLING_AND_RATE+5)
		#define	CMD_I_WS_SAMPLING_RATE_A6				(STARTOFRANGE_SET_SAMPLING_AND_RATE+6)
		#define	CMD_I_WS_SAMPLING_RATE_A7				(STARTOFRANGE_SET_SAMPLING_AND_RATE+7)
		#define	CMD_I_WS_SAMPLING_RATE_B0				(STARTOFRANGE_SET_SAMPLING_AND_RATE+8)
		#define	CMD_I_WS_SAMPLING_RATE_B1				(STARTOFRANGE_SET_SAMPLING_AND_RATE+9)
		#define	CMD_I_WS_SAMPLING_RATE_B2				(STARTOFRANGE_SET_SAMPLING_AND_RATE+10)
		#define	CMD_I_WS_SAMPLING_RATE_B3				(STARTOFRANGE_SET_SAMPLING_AND_RATE+11)
		#define	CMD_I_WS_SAMPLING_RATE_B4				(STARTOFRANGE_SET_SAMPLING_AND_RATE+12)
		#define	CMD_I_WS_SAMPLING_RATE_B5				(STARTOFRANGE_SET_SAMPLING_AND_RATE+13)
		#define	CMD_I_WS_SAMPLING_RATE_B6				(STARTOFRANGE_SET_SAMPLING_AND_RATE+14)
		#define	CMD_I_WS_SAMPLING_RATE_B7				(STARTOFRANGE_SET_SAMPLING_AND_RATE+15)
		#define	CMD_I_WS_SAMPLING_RATE_C0				(STARTOFRANGE_SET_SAMPLING_AND_RATE+16)
		#define	CMD_I_WS_SAMPLING_RATE_C1				(STARTOFRANGE_SET_SAMPLING_AND_RATE+17)
		#define	CMD_I_WS_SAMPLING_RATE_C2				(STARTOFRANGE_SET_SAMPLING_AND_RATE+18)
		#define	CMD_I_WS_SAMPLING_RATE_C3				(STARTOFRANGE_SET_SAMPLING_AND_RATE+19)
		#define	CMD_I_WS_SAMPLING_RATE_C4				(STARTOFRANGE_SET_SAMPLING_AND_RATE+20)
		#define	CMD_I_WS_SAMPLING_RATE_C5				(STARTOFRANGE_SET_SAMPLING_AND_RATE+21)
		#define	CMD_I_WS_SAMPLING_RATE_C6				(STARTOFRANGE_SET_SAMPLING_AND_RATE+22)
		#define	CMD_I_WS_SAMPLING_RATE_C7				(STARTOFRANGE_SET_SAMPLING_AND_RATE+23)
		#define	CMD_I_WS_SAMPLING_RATE_D0				(STARTOFRANGE_SET_SAMPLING_AND_RATE+24)
		#define	CMD_I_WS_SAMPLING_RATE_D1				(STARTOFRANGE_SET_SAMPLING_AND_RATE+25)
		#define	CMD_I_WS_SAMPLING_RATE_D2				(STARTOFRANGE_SET_SAMPLING_AND_RATE+26)
		#define	CMD_I_WS_SAMPLING_RATE_D3				(STARTOFRANGE_SET_SAMPLING_AND_RATE+27)
		#define	CMD_I_WS_SAMPLING_RATE_D4				(STARTOFRANGE_SET_SAMPLING_AND_RATE+28)
		#define	CMD_I_WS_SAMPLING_RATE_D5				(STARTOFRANGE_SET_SAMPLING_AND_RATE+29)
		#define	CMD_I_WS_SAMPLING_RATE_D6				(STARTOFRANGE_SET_SAMPLING_AND_RATE+30)
		#define	CMD_I_WS_SAMPLING_RATE_D7				(STARTOFRANGE_SET_SAMPLING_AND_RATE+31)

		
		/* INBOUND CMD [READ] (MULTIBYTE) */
		#define	CMD_I_RM_MAGDATA						(34u) // STARTOFRANGE_READ_TYPE = 34u --> 40u
		
		/* INBOUND CMD [READ] (SINGLE BYTE) */
		#define	CMD_I_RS_CTRL1							(35u)
		#define	CMD_I_RS_CTRL2							(36u)
		#define	CMD_I_RS_DRSTATUS						(37u)
		#define	CMD_I_RS_SYSMOD							(38u)
		#define	CMD_I_RS_DIETEMP						(39u)
		#define	CMD_I_RS_WHOAMI							(40u)

		
		/*INBOUND CMD [WRITE] (SINGLE) CTRLREG1 */
		#define CMD_I_WS_CTRL1_DEFAULT					(41u) //STARTOFRANGE_SET_CTRL1_OTHER_TYPE = 41u --> 47u
		#define CMD_I_WS_CTRL1_MODSTANDBY				(42u)
		#define CMD_I_WS_CTRL1_MODSINGLE				(43u)
		#define CMD_I_WS_CTRL1_MODACTIVE				(44u)
		#define CMD_I_WS_CTRL1_MODTRIGGER				(45u)
		#define CMD_I_WS_CTRL1_ENFAST					(46u)
		#define CMD_I_WS_CTRL1_NENFAST					(47u)
		
		/*INBOUND CMD [WRITE] (SINGLE) CTRLREG2 */
		#define CMD_I_WS_CTRL2_DEFAULT					(48u) //STARTOFRANGE_SET_CTRL2_TYPE = 48u --> 53u
		#define CMD_I_WS_CTRL2_ENAUTORESET				(49u)
		#define CMD_I_WS_CTRL2_NENAUTORESET				(50u)
		#define CMD_I_WS_CTRL2_ENUSEROFFSET				(51u)
		#define CMD_I_WS_CTRL2_NENUSEROFFSET			(52u)
		#define CMD_I_WS_CTRL2_RESETMAG					(53u)
		
		//Reset ALL
		#define CMD_I_RESET_ALL							(54u)

		//===============
		
		/* OUTBOUND CMD */
		#define CMD_O_MAGDATARDY						(55u) //STARTOFRANGE_OUTBOUND_CMD = 55u --> 59u
		#define CMD_O_BUSY								(56u)
		#define CMD_O_ARRAY_TIMEOUT						(57u)
		#define CMD_O_ERR_MAGREAD						(58u)
		#define CMD_O_ERR_MAGWRIT						(59u)
		#define CMD_O_CMDVALUEOUTOFRANGE				(60u)	
	
	/* END: COMMAND CODE VALUES in #define */
	
	// Define API Values
	
	/* MAG Data Array Size in Bytes */
	#define ARRAY_SIZE_MAG_DATA		(6u)
    
    //FUNCTION PROTOTYPES
    CY_ISR_PROTO(XBeeISR);
    CY_ISR_PROTO(INT1PinISR);
    
    //UTILITY FUNCTIONS
    void InitXBee_Isr(void);
    void InitINT1_Isr(void);
    

#endif 
/* [] END OF FILE */
